### ISSUE TITLE
inaccurate answer and possible bug not redering answer properly

### ISSUE THREAD

**Issue by jnordwick** [warpdotdev/workflows#104] opened 2022-08-06 18:12 UTC
### Is this a new workflow or an update?

Update

### What is the name of the workflow?

Find all files in a directory that don't contain a string

### What should the workflow do?

find ALL files

### What does it do (only if it's an update)?

find only files not starting with dot

**Comment by QuentinMoss** [comment] 2022-10-19 00:28
I believe this was fixed on the preview build as I was unable to reproduce, so should make its way to main build soon.

**Comment by dannyneira** [comment] 2022-12-06 17:04
@jnordwick Are you still seeing the same issue with the workflow?

**Comment by alokedesai** [comment] 2023-01-13 23:35
@jnordwick friendly ping on this! Would love to close this out if you are unable to repro

**Comment by jnordwick** [comment] 2023-01-25 10:36
I'm sorry I wouldn't know I haven't tried this in a while. But please feel
free to close it out Don't keep it open for me

**Comment by alokedesai** [comment] 2023-01-25 14:19
Great, i'll go ahead and close this out. Please reopen if you start experiencing this issue again!

**Closed by alokedesai** 2023-01-25 14:19 UTC
Labels: enhancement

**Comment by jnordwick** [comment] 2023-01-25 20:58
I might install this again just check it out watch out Make sure chat GPT
doesn't eat your lunch
